In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.listdir("New folder")

['customers.csv',
 'locations.csv',
 'orders.csv',
 'order_items.csv',
 'payments.csv',
 'products.csv',
 'README_DATA.txt',
 'returns.csv',
 'sellers.csv',
 'shipping.csv']

In [3]:
customers = pd.read_csv("New folder/customers.csv")

customers.head()

,customer_id,full_name,email,phone,gender,registration_date,city_id,birth_year
0,C000001,Nida Memon,nida.memon6133@yahoo.com,0343-4328042,F,2024-02-04,614.0,1996.0
1,C000002,rizwan ansari,rizwan.ansari7047@gmail.com,03292755530,m,03/02/2025,310.0,1977.0
2,C000003,Noor Baig,noor.baig763@gmail.com,330 2812162,F,2024-01-31,347.0,1999.0
3,C000004,Naveed Hashmi,naveed.hashmi9719@gmail.com,03128373694,M,2024-07-18,570.0,1985.0
4,C000005,Mahnoor Mirza,mahnoor.mirza5501@yahoo.com,03251346045,F,2024-04-07,614.0,1989.0

In [4]:
customers.shape

(45000, 8)

In [5]:
folder = "New folder"

files = [
    "customers.csv",
    "products.csv",
    "sellers.csv",
    "locations.csv",
    "orders.csv",
    "order_items.csv",
    "payments.csv",
    "shipping.csv",
    "returns.csv"
]

data = {}

for file in files:
    data[file.replace(".csv", "")] = pd.read_csv(
        os.path.join(folder, file)
    )

print("All files loaded successfully!")

All files loaded successfully!

In [6]:
for name, df in data.items():
    print(f"{name:15} → {df.shape[0]:,} rows × {df.shape[1]} columns")

customers       → 45,000 rows × 8 columns
products        → 3,200 rows × 9 columns
sellers         → 420 rows × 6 columns
locations       → 650 rows × 7 columns
orders          → 163,200 rows × 8 columns
order_items     → 315,143 rows × 7 columns
payments        → 168,111 rows × 6 columns
shipping        → 151,228 rows × 7 columns
returns         → 16,048 rows × 6 columns

In [7]:
for name, df in data.items():
    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)
    print(df.columns.tolist())

============================================================
CUSTOMERS
============================================================
['customer_id', 'full_name', 'email', 'phone', 'gender', 'registration_date', 'city_id', 'birth_year']

============================================================
PRODUCTS
============================================================
['product_id', 'product_name', 'category', 'sub_category', 'brand', 'list_price', 'cost_price', 'weight_kg', 'seller_id']

============================================================
SELLERS
============================================================
['seller_id', 'seller_name', 'join_date', 'seller_tier', 'city_id', 'rating']

============================================================
LOCATIONS
============================================================
['city_id', 'city', 'province', 'region', 'latitude', 'longitude', 'population_tier']

============================================================
ORDERS
============================================================
['order_id', 'customer_id', 'order_date', 'order_status', 'ship_city_id', 'order_total', 'discount_code', 'channel']

============================================================
ORDER_ITEMS
============================================================
['order_item_id', 'order_id', 'product_id', 'seller_id', 'quantity', 'unit_price', 'discount_amount']

============================================================
PAYMENTS
============================================================
['payment_id', 'order_id', 'payment_method', 'payment_status', 'amount', 'payment_date']

============================================================
SHIPPING
============================================================
['shipment_id', 'order_id', 'courier', 'shipped_date', 'delivered_date', 'shipping_fee', 'delivery_status']

============================================================
RETURNS
============================================================
['return_id', 'order_item_id', 'return_date', 'return_reason', 'return_status', 'refund_amount']

In [8]:
for name, df in data.items():
    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)
    display(df.head(3))

============================================================
CUSTOMERS
============================================================

,customer_id,full_name,email,phone,gender,registration_date,city_id,birth_year
0,C000001,Nida Memon,nida.memon6133@yahoo.com,0343-4328042,F,2024-02-04,614.0,1996.0
1,C000002,rizwan ansari,rizwan.ansari7047@gmail.com,03292755530,m,03/02/2025,310.0,1977.0
2,C000003,Noor Baig,noor.baig763@gmail.com,330 2812162,F,2024-01-31,347.0,1999.0

============================================================
PRODUCTS
============================================================

,product_id,product_name,category,sub_category,brand,list_price,cost_price,weight_kg,seller_id
0,P00001,MobiPro USB-C Cable L740,Mobile & Accessories,Mobile Essentials,MobiPro,980,577.0,0.39,S0411
1,P00002,NexusChoice Sneakers I796,Footwear,Footwear Basics,NexusChoice,6990,NaN,0.98,S0130
2,P00003,Zeta Polo Shirt T44,Fashion,Fashion Premium,Zeta,1960,1122.0,-1.00,S0322

============================================================
SELLERS
============================================================

  seller_id           seller_name   join_date seller_tier  city_id  rating
0     S0001    Karachi Traders 84  2023-07-17        Gold      597     4.1
1     S0002  Crown Collection 32   2020-02-14      Silver       86     4.1
2     S0003          Metro Mart 5  2022-10-16      Bronze      450     3.9

============================================================
LOCATIONS
============================================================

,city_id,city,province,region,latitude,longitude,population_tier
0,1,PurPurPur,Sindh,South,26.1297,68.2655,Tier-3
1,2,SaraiTandoKot,Punjab,Central,31.3893,73.2073,Tier-3
2,3,WalaSaraiBasti,Punjab,Central,31.8080,71.8958,Tier-3

============================================================
ORDERS
============================================================

,order_id,customer_id,order_date,order_status,ship_city_id,order_total,discount_code,channel
0,O0106517,C042364,2025-02-04,DELIVERD,316.0,5206,NaN,Website
1,O0129677,C022887,2025-04-06,Delivered,347.0,675,NaN,App
2,O0083748,C010022,Nov 23 2024,Delivered,281.0,2362,NaN,Web

============================================================
ORDER_ITEMS
============================================================

,order_item_id,order_id,product_id,seller_id,quantity,unit_price,discount_amount
0,OI00000001,O0000001,P02548,S0310,1,"Rs. 2,290",0.0
1,OI00000002,O0000001,P01857,S0197,1,5850,0.0
2,OI00000003,O0000002,P01761,S0243,1,1900,0.0

============================================================
PAYMENTS
============================================================

    payment_id  order_id payment_method payment_status amount payment_date
0  PAY00048624  O0047146            COD           Paid   1270   2024-07-19
1  PAY00084629  O0082098       JazzCash           Paid   3747   2024-11-17
2  PAY00140975  O0136814     Debit Card           Paid   8745   2025-04-29

============================================================
SHIPPING
============================================================

,shipment_id,order_id,courier,shipped_date,delivered_date,shipping_fee,delivery_status
0,SH00000001,O0000001,M&P,2024-01-02,2024-01-06,823.0,DELIVERD
1,SH00000002,O0000002,Leopards,2024-01-02,2024-01-04,309.0,Delivered
2,SH00000003,O0000003,Leopards,2024-01-02,2024-01-05,459.0,Delivered

============================================================
RETURNS
============================================================

,return_id,order_item_id,return_date,return_reason,return_status,refund_amount
0,R000001,OI00000155,2024-01-06,Not as described,Refunded,1020
1,R000002,OI00000220,2024-01-07,Size/fit issue,REFUNDED,1558
2,R000003,OI00000308,2024-01-07,NaN,Approved,3050

In [9]:

for name, df in data.items():
    print(f"\n{'='*50}")
    print(f"Dataset: {name}")
    print("="*50)
    print(df.dtypes)

==================================================
Dataset: customers
==================================================
customer_id           object
full_name             object
email                 object
phone                 object
gender                object
registration_date     object
city_id              float64
birth_year           float64
dtype: object

==================================================
Dataset: products
==================================================
product_id       object
product_name     object
category         object
sub_category     object
brand            object
list_price       object
cost_price      float64
weight_kg       float64
seller_id        object
dtype: object

==================================================
Dataset: sellers
==================================================
seller_id       object
seller_name     object
join_date       object
seller_tier     object
city_id          int64
rating         float64
dtype: object

==================================================
Dataset: locations
==================================================
city_id              int64
city                object
province            object
region              object
latitude           float64
longitude          float64
population_tier     object
dtype: object

==================================================
Dataset: orders
==================================================
order_id          object
customer_id       object
order_date        object
order_status      object
ship_city_id     float64
order_total       object
discount_code     object
channel           object
dtype: object

==================================================
Dataset: order_items
==================================================
order_item_id       object
order_id            object
product_id          object
seller_id           object
quantity            object
unit_price          object
discount_amount    float64
dtype: object

==================================================
Dataset: payments
==================================================
payment_id        object
order_id          object
payment_method    object
payment_status    object
amount            object
payment_date      object
dtype: object

==================================================
Dataset: shipping
==================================================
shipment_id         object
order_id            object
courier             object
shipped_date        object
delivered_date      object
shipping_fee       float64
delivery_status     object
dtype: object

==================================================
Dataset: returns
==================================================
return_id        object
order_item_id    object
return_date      object
return_reason    object
return_status    object
refund_amount    object
dtype: object

In [10]:
for name, df in data.items():
    print(f"\n{name.upper()}")
    missing = df.isnull().sum()
    missing = missing[missing > 0]

    if missing.empty:
        print("No missing values found.")
    else:
        print(missing.sort_values(ascending=False))

CUSTOMERS
birth_year    4600
phone         3599
city_id       2233
gender        2199
email         1698
dtype: int64

PRODUCTS
sub_category    485
brand           392
weight_kg       296
cost_price      170
dtype: int64

SELLERS
join_date      34
rating         33
seller_tier    22
dtype: int64

LOCATIONS
latitude     33
longitude    31
province     25
dtype: int64

ORDERS
discount_code    112059
ship_city_id       6516
dtype: int64

ORDER_ITEMS
discount_amount    31567
dtype: int64

PAYMENTS
payment_date    5017
dtype: int64

SHIPPING
delivered_date    18841
shipping_fee       9145
shipped_date       5943
dtype: int64

RETURNS
return_reason    2390
dtype: int64

In [11]:
for name, df in data.items():
    print(f"{name:15} → {df.duplicated().sum():,} duplicate rows")

customers       → 0 duplicate rows
products        → 0 duplicate rows
sellers         → 0 duplicate rows
locations       → 0 duplicate rows
orders          → 3,200 duplicate rows
order_items     → 0 duplicate rows
payments        → 3,296 duplicate rows
shipping        → 0 duplicate rows
returns         → 0 duplicate rows

In [12]:
for name in ["orders", "payments"]:
    df = data[name]

    print(f"\n{'='*50}")
    print(f"Dataset: {name.upper()}")
    print("="*50)

    # Show duplicate records, including the original rows
    duplicates = df[df.duplicated(keep=False)]

    print("Rows involved in exact duplicates:", len(duplicates))
    display(duplicates.head(10))

    # Check whether the primary ID is duplicated
    id_col = "order_id" if name == "orders" else "payment_id"

    print(f"Duplicate {id_col} values:", df[id_col].duplicated().sum())

==================================================
Dataset: ORDERS
==================================================
Rows involved in exact duplicates: 6400

,order_id,customer_id,order_date,order_status,ship_city_id,order_total,discount_code,channel
10,O0018251,C036817,2024-03-30,Cancelled,375.0,11675,NaN,Web
21,O0025356,C040589,2024-04-21,Delivered,346.0,15682,NaN,App
27,O0016395,C001421,2024-03-23,Complete,535.0,36444,NaN,App
65,O0136515,C019821,2025-04-28,Complete,NaN,1830,NaN,App
70,O0045454,C009138,2024-07-11,Returned,450.0,2905,NaN,Mobile Web
79,O0007344,C027950,2024-02-10,Complete,614.0,2920,NaN,Mobile Web
93,O0029102,C026910,2024-05-08,Delivered,614.0,6346,NaN,App
95,O0004599,C037039,2024-01-26,Complete,421.0,1944,NaN,Web
98,O0026655,C011501,27/04/2024,Delivered,434.0,777,NaN,App
110,O0103291,C008165,Jan 24 2025,DELIVERED,450.0,764,NaN,App

Duplicate order_id values: 3200

==================================================
Dataset: PAYMENTS
==================================================
Rows involved in exact duplicates: 6592

     payment_id  order_id    payment_method payment_status amount payment_date
13  PAY00028793  O0027897               COD           Paid   3030   2024-05-06
21  PAY00013539  O0013128     Bank Transfer           Paid   3128   2024-03-11
22  PAY00048432  O0046958     Bank Transfer           Paid  15507   2024-07-17
35  PAY00031741  O0030766               COD      Cancelled   7351   2024-05-21
42  PAY00004911  O0004782               COD           Paid   4327   2024-01-30
45  PAY00005975  O0005812               COD           Paid   6436          NaN
62  PAY00042971  O0041667               cod           Paid    862  Jun 30 2024
70  PAY00025810  O0025011               COD           Paid   4486   2024-04-21
74  PAY00078227  O0075897  Cash on Delivery           Paid  29541   2024-11-03
75  PAY00003149  O0003065          JazzCash           Paid   2423          NaN

Duplicate payment_id values: 3296

In [13]:

numeric_columns = {
    "products": ["list_price", "cost_price", "weight_kg"],
    "orders": ["order_total"],
    "order_items": ["quantity", "unit_price", "discount_amount"],
    "payments": ["amount"],
    "returns": ["refund_amount"]
}

for name, columns in numeric_columns.items():
    print(f"\n{'='*40}")
    print(f"Dataset: {name.upper()}")

    for col in columns:
        df = data[name]
        converted = pd.to_numeric(df[col], errors="coerce")

        invalid = df[col].notna() & converted.isna()

        print(f"\n{col}")
        print("Invalid numeric values:", invalid.sum())

        if invalid.any():
            print("Examples:", df.loc[invalid, col].unique()[:10])

========================================
Dataset: PRODUCTS

list_price
Invalid numeric values: 105
Examples: ['Rs. 690' 'Rs. 2,900' 'Rs. 1,690' 'Rs. 1,750' 'Rs. 5,980' 'Rs. 11,190'
 'Rs. 6,870' 'Rs. 4,120' 'Rs. 3,650' 'Rs. 510']

cost_price
Invalid numeric values: 0

weight_kg
Invalid numeric values: 0

========================================
Dataset: ORDERS

order_total
Invalid numeric values: 4028
Examples: ['Rs. 6,398' 'Rs. 4,710' 'Rs. 9,438' 'Rs. 3,087' 'Rs. 28,380' 'Rs. 8,106'
 'Rs. 2,004' 'Rs. 8,363' 'Rs. 5,534' 'Rs. 21,228']

========================================
Dataset: ORDER_ITEMS

quantity
Invalid numeric values: 965
Examples: ['one' 'three' 'four' 'two' 'five']

unit_price
Invalid numeric values: 7998
Examples: ['Rs. 2,290' 'Rs. 910' 'Rs. 300' 'Rs. 640' 'Rs. 1,560' 'Rs. 280'
 'Rs. 1,210' 'Rs. 4,849' 'Rs. 1,800' 'Rs. 2,050']

discount_amount
Invalid numeric values: 0

========================================
Dataset: PAYMENTS

amount
Invalid numeric values: 4210
Examples: ['Rs. 47,397' 'Rs. 9,855' 'Rs. 2,151' 'Rs. 36,291' 'Rs. 878' 'Rs. 2,320'
 'Rs. 175' 'Rs. 876' 'Rs. 11,024' 'Rs. 5,262']

========================================
Dataset: RETURNS

refund_amount
Invalid numeric values: 428
Examples: ['Rs. 1,500' 'Rs. 1,608' 'Rs. 410' 'Rs. 1,893' 'Rs. 10,082' 'Rs. 9,061'
 'Rs. 1,923' 'Rs. 2,377' 'Rs. 1,682' 'Rs. 3,356']

In [14]:

for name, df in data.items():
    missing_pct = (df.isnull().mean() * 100).round(2)
    missing_pct = missing_pct[missing_pct > 0]
    missing_pct = missing_pct.sort_values(ascending=False)

    print(f"\n{name.upper()} — Missing Values (%)")
    display(missing_pct.to_frame(name="Missing %"))

CUSTOMERS — Missing Values (%)

            Missing %
birth_year      10.22
phone            8.00
city_id          4.96
gender           4.89
email            3.77

PRODUCTS — Missing Values (%)

              Missing %
sub_category      15.16
brand             12.25
weight_kg          9.25
cost_price         5.31

SELLERS — Missing Values (%)

             Missing %
join_date         8.10
rating            7.86
seller_tier       5.24

LOCATIONS — Missing Values (%)

           Missing %
latitude        5.08
longitude       4.77
province        3.85

ORDERS — Missing Values (%)

               Missing %
discount_code      68.66
ship_city_id        3.99

ORDER_ITEMS — Missing Values (%)

                 Missing %
discount_amount      10.02

PAYMENTS — Missing Values (%)

              Missing %
payment_date       2.98

SHIPPING — Missing Values (%)

                Missing %
delivered_date      12.46
shipping_fee         6.05
shipped_date         3.93

RETURNS — Missing Values (%)

               Missing %
return_reason      14.89